### ISSUE TITLE
[Scheduled Maintenance] Wartungsarbeiten von JH-Computers

### ISSUE THREAD

**Issue by berendt** [regiocloud/status#3]
Es werden geplante Wartungsarbeiten von JH-Computers an der Router Infrastruktur ausgeführt. Die von JH-Computers erwartete Ausfallzeit beträgt 5 Minuten.

**Comment by osfrickler** [comment]
Die Wartung wurde erfolgreich abgeschlossen, der Ausfall dauerte 5 Minuten.
