### ISSUE TITLE
[Scheduled Maintenance] OpenStack Octavia (LBaaS) maintenance

### ISSUE THREAD

**Issue by berendt** [regiocloud/status#4]
Es werden geplante Wartungsarbeiten von OSISM GmbH am OpenStack Octavia (LBaaS) Service ausgeführt. Im Wartungszeitraum wird es mehrmalig zu Verbindungsabbrüchen in ein- und ausgehender Richtung auf den Loadbalancern kommen.

**Comment by osfrickler** [comment]
Die Wartungsarbeiten wurden abgeschlossen, alle Dienste funktionieren wieder fehlerfrei. Es konnte nur ein Teil der Arbeiten durchgeführt werden, da es im Verlauf zu unerwarteten Problemen kam. Wir werden diese Probleme untersuchen und zu gegebener Zeit ein neues Wartungsfenster einplanen.
